/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.colaborador.administradores;

import estructuras.arboles.b.subestructuras.cola.ColaB;
import estructuras.listas.simples.ListaS;
import estructuras.listas.simples.NodoS;
import interfaz.colaborador.AreaColaborador;
import javax.swing.JOptionPane;
import pojos.Estudiante;

/**
 *
 * @author g
 */
public class Asignaciones extends javax.swing.JFrame {

    /**
     * Creates new form Asignacion
     */
    public Asignaciones() {
        initComponents();
        llenarCBs();
    }
    
    public void llenarCBs(){
        if(!estructuras.Estructuras.th_estudiantes.esVacia()){
            for (Estudiante e : estructuras.Estructuras.th_estudiantes.tabla) {
                if(e != null){
                    carnet_cb.addItem(String.valueOf(e.getCarnet()));
                }
            }
        }
        if(!estructuras.Estructuras.b_horarios.esVacio()){
            ColaB cola_auxiliar = estructuras.Estructuras.b_horarios.listar();
            int tamano_cola = estructuras.Estructuras.b_horarios.listar().getTamano();
            for(int i = 0; i < tamano_cola; i++){
                codigo_horario_cb.addItem(String.valueOf(cola_auxiliar.desencolar()
                .getHorario().getCodigo()));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        asignacion_titulo_lb = new javax.swing.JLabel();
        asignacion_info_lb = new javax.swing.JLabel();
        carnet_lb = new javax.swing.JLabel();
        codigo_horario_lb = new javax.swing.JLabel();
        carnet_cb = new javax.swing.JComboBox<>();
        codigo_horario_cb = new javax.swing.JComboBox<>();
        zona_lb = new javax.swing.JLabel();
        zona_txt = new javax.swing.JTextField();
        final_lb = new javax.swing.JLabel();
        final_txt = new javax.swing.JTextField();
        agregar_bt = new javax.swing.JButton();
        volver_bt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        asignacion_titulo_lb.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        asignacion_titulo_lb.setText("Administracion de asignaciones");

        asignacion_info_lb.setText("Elige la accion que deseas realizar");

        carnet_lb.setText("Carnet");

        codigo_horario_lb.setText("Codigo horario");

        zona_lb.setText("Zona");

        final_lb.setText("Final");

        agregar_bt.setText("Agregar");
        agregar_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_btActionPerformed(evt);
            }
        });

        volver_bt.setText("Volver");
        volver_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver_btActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(asignacion_titulo_lb)
                    .addComponent(carnet_lb)
                    .addComponent(codigo_horario_lb)
                    .addComponent(carnet_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zona_lb)
                    .addComponent(final_lb)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(final_txt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(zona_txt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(codigo_horario_cb, javax.swing.GroupLayout.Alignment.LEADING, 0, 205, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(agregar_bt)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(volver_bt))
                        .addComponent(asignacion_info_lb, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(asignacion_titulo_lb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(asignacion_info_lb)
                .addGap(18, 18, 18)
                .addComponent(carnet_lb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carnet_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codigo_horario_lb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(codigo_horario_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zona_lb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zona_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(final_lb)
                .addGap(18, 18, 18)
                .addComponent(final_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar_bt)
                    .addComponent(volver_bt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volver_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver_btActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AreaColaborador().setVisible(true);
    }//GEN-LAST:event_volver_btActionPerformed

    private void agregar_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_btActionPerformed
        // TODO add your handling code here:
        if(!zona_txt.getText().isEmpty() || !final_txt.getText().isEmpty()){
            
            int carnet = Integer.parseInt(carnet_cb.getSelectedItem().toString());
            int codigo_horario = Integer.parseInt(codigo_horario_cb.getSelectedItem().toString());
            int zona = Integer.parseInt(zona_txt.getText());
            int nota_final = Integer.parseInt(final_txt.getText());
            
            if(estructuras.Estructuras.b_horarios.buscarPorParametro(codigo_horario) != null){
                try {
                    if(estructuras.Estructuras.b_horarios.buscarPorParametro(codigo_horario).getAsignaciones() != null 
                    || !estructuras.Estructuras.b_horarios.buscarPorParametro(codigo_horario).getAsignaciones().esVacia()){
                        ListaS lista_asignaciones_temporales = new ListaS();

                        lista_asignaciones_temporales.insertar(
                        new NodoS(new pojos.Asignacion(carnet, codigo_horario, zona, nota_final), 
                        estructuras.Estructuras.th_estudiantes.buscar(carnet)));

                        estructuras.Estructuras.b_horarios.
                        buscarPorParametro(codigo_horario).
                        setAsignaciones(lista_asignaciones_temporales);
                    }else{
                        estructuras.Estructuras.b_horarios.
                        buscarPorParametro(codigo_horario).
                        getAsignaciones().insertar(new NodoS(
                        new pojos.Asignacion(carnet, codigo_horario, zona, nota_final),
                        estructuras.Estructuras.th_estudiantes.buscar(carnet)));
                    }
                    JOptionPane.showMessageDialog(null, "Se ingreso correctamente la asignacion del carnet: "
                    + carnet + ", al horario: " + codigo_horario + ".", 
                    "Muy bien", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    System.out.println("No tiene asignaciones");
                }
                
            }else{
                JOptionPane.showMessageDialog(null, "No se ingreso la asignacion del carnet: "
                + carnet + ", porque ya existe este en el horario: " + codigo_horario + ".", 
                "Atencion", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "¡Hay campos vacios!",
            "Atencion", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_agregar_btActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asignaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asignaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asignaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asignaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asignaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar_bt;
    private javax.swing.JLabel asignacion_info_lb;
    private javax.swing.JLabel asignacion_titulo_lb;
    private javax.swing.JComboBox<String> carnet_cb;
    private javax.swing.JLabel carnet_lb;
    private javax.swing.JComboBox<String> codigo_horario_cb;
    private javax.swing.JLabel codigo_horario_lb;
    private javax.swing.JLabel final_lb;
    private javax.swing.JTextField final_txt;
    private javax.swing.JButton volver_bt;
    private javax.swing.JLabel zona_lb;
    private javax.swing.JTextField zona_txt;
    // End of variables declaration//GEN-END:variables
}
