/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.colaborador;

import interfaz.colaborador.administradores.Cursos;
import interfaz.colaborador.administradores.Edificios;
import interfaz.colaborador.administradores.Usuarios;
import interfaz.colaborador.administradores.Estudiantes;
import estructuras.Estructuras;
import interfaz.Login;
import javax.swing.JOptionPane;

/**
 *
 * @author g
 */
public class AreaColaborador extends javax.swing.JFrame {

    /**
     * Creates new form Colaborador
     */
    public AreaColaborador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo_area_colaborador_lb = new javax.swing.JLabel();
        info_area_colaborador_lb = new javax.swing.JLabel();
        administrar_btn = new javax.swing.JButton();
        administrar_cb = new javax.swing.JComboBox<>();
        volver_bt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Area de trabajo de colaborador");

        titulo_area_colaborador_lb.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        titulo_area_colaborador_lb.setText("Bienvenido al area de colaborador");

        info_area_colaborador_lb.setText("Elige lo que deseas administrar");

        administrar_btn.setText("Administrar");
        administrar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administrar_btnActionPerformed(evt);
            }
        });

        administrar_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuarios", "Edificios", "Cursos", "Estudiantes", "Catedraticos", "Asignacion" }));

        volver_bt.setText("Volver");
        volver_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver_btActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(volver_bt)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(info_area_colaborador_lb)
                        .addComponent(titulo_area_colaborador_lb)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(administrar_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(administrar_btn))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(titulo_area_colaborador_lb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(info_area_colaborador_lb)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(administrar_btn)
                    .addComponent(administrar_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(volver_bt)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void administrar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administrar_btnActionPerformed
        // TODO add your handling code here:
        String administrar_elegido = administrar_cb.getSelectedItem().toString();
        /*
            Usuarios
            Edificios y salones
            Cursos
            Estudiantes
            Catedraticos
            Asignacion
        */
        switch(administrar_elegido){
            case "Usuarios":
                if(!estructuras.Estructuras.ldo_usuarios.esVacia()){
                    this.setVisible(false);
                    new Usuarios().setVisible(true);
                }else{
                    JOptionPane.showMessageDialog(null, "¡No se han cargado los usuarios!", 
                    "Atencion", JOptionPane.WARNING_MESSAGE);
                }
                break;
            case "Edificios":
                if(!estructuras.Estructuras.ldc_edificios.esVacia()){
                    this.setVisible(false);
                    new Edificios().setVisible(true);
                }else{
                    JOptionPane.showMessageDialog(null, "¡No se han cargado los edificios y salones!", 
                    "Atencion", JOptionPane.WARNING_MESSAGE);
                }
                break;
            case "Cursos":
                if(!estructuras.Estructuras.lso_cursos.esVacia()){
                    this.setVisible(false);
                    new Cursos().setVisible(true);
                }else{
                    JOptionPane.showMessageDialog(null, "¡No se han cargado los cursos!", 
                    "Atencion", JOptionPane.WARNING_MESSAGE);
                }
                break;
            case "Estudiantes":
                if(!estructuras.Estructuras.th_estudiantes.esVacia()){
                    this.setVisible(false);
                    new Estudiantes().setVisible(true);
                }else{
                    JOptionPane.showMessageDialog(null, "¡No se han cargado los estudiantes!", 
                    "Atencion", JOptionPane.WARNING_MESSAGE);
                }
                break;
            case "Catedraticos":
                if(!estructuras.Estructuras.avl_catedraticos.esVacio()){
                    
                }else{
                    JOptionPane.showMessageDialog(null, "¡No se han cargado los catedraticos!", 
                    "Atencion", JOptionPane.WARNING_MESSAGE);
                }
                break;
            case "Asignacion":
                if(!estructuras.Estructuras.b_horarios.esVacio()){
                    
                }else{
                    JOptionPane.showMessageDialog(null, "¡No se han cargado los horarios y asignaciones!", 
                    "Atencion", JOptionPane.WARNING_MESSAGE);
                }
                break;
        }
    }//GEN-LAST:event_administrar_btnActionPerformed

    private void volver_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver_btActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_volver_btActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AreaColaborador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton administrar_btn;
    private javax.swing.JComboBox<String> administrar_cb;
    private javax.swing.JLabel info_area_colaborador_lb;
    private javax.swing.JLabel titulo_area_colaborador_lb;
    private javax.swing.JButton volver_bt;
    // End of variables declaration//GEN-END:variables
}
